#!/usr/bin/with-contenv bash
# shellcheck shell=bash
. "/usr/local/bin/logger"
# ==============================================================================
# Neo ZM Event Notification Server
# Runs ES in foreground
# ==============================================================================

ES_FLAGS=("--docker" "--config=/config/zmeventnotification.ini")

if [ "${ES_DEBUG_ENABLED}" -eq 1 ]; then
  echo "Enabling ES Debug!" | info
  ES_FLAGS+=("--debug")
fi

echo "Waiting for ZoneMinder to start..." | info
/bin/s6-svwait -U /var/run/s6/services/zoneminder

echo "Starting Event Server with FLAGS = ${ES_FLAGS[*]}" | info
fdmove -c 1 3 /usr/bin/zmeventnotification.pl "${ES_FLAGS[@]}"
